# Generated by Django 2.1.4 on 2020-04-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=264)),
                ('Age', models.IntegerField()),
                ('Password', models.CharField(max_length=264)),
            ],
        ),
    ]
