# Generated by Django 2.1.4 on 2020-05-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('Name', models.CharField(max_length=264)),
                ('UserName', models.CharField(max_length=264, primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Password', models.CharField(max_length=264)),
            ],
        ),
    ]
