# Generated by Django 2.1.4 on 2020-05-31 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('Name', models.CharField(max_length=264)),
                ('UserName', models.CharField(max_length=264, primary_key=True, serialize=False)),
                ('Class', models.CharField(max_length=10)),
                ('Section', models.CharField(max_length=1)),
                ('Gender', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Percentage', models.IntegerField()),
                ('Password', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.SignUp')),
            ],
        ),
        migrations.CreateModel(
            name='Test1Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=512)),
                ('yes', models.IntegerField()),
                ('no', models.IntegerField()),
                ('notSure', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeReq', models.DurationField(blank=True, db_index=True, null=True)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.SignUp')),
            ],
        ),
    ]
