# Generated by Django 2.1.4 on 2020-05-10 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200504_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='UserName',
            field=models.CharField(default=django.utils.timezone.now, max_length=264),
            preserve_default=False,
        ),
    ]
