# Generated by Django 2.1.4 on 2020-05-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_signup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='id',
        ),
        migrations.AlterField(
            model_name='signup',
            name='UserName',
            field=models.CharField(max_length=264, primary_key=True, serialize=False),
        ),
    ]
