# Generated by Django 2.1.4 on 2020-05-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_test1questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test1Questions',
            new_name='Test1Question',
        ),
    ]
