# Generated by Django 2.1.4 on 2020-05-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200524_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1question',
            name='option1',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test1question',
            name='option2',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test1question',
            name='option3',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
