# Generated by Django 2.1.4 on 2020-05-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200524_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test1question',
            old_name='option1',
            new_name='no',
        ),
        migrations.RenameField(
            model_name='test1question',
            old_name='option2',
            new_name='notSure',
        ),
        migrations.RenameField(
            model_name='test1question',
            old_name='option3',
            new_name='yes',
        ),
    ]
