# Generated by Django 2.1.4 on 2020-05-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200524_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.SignUp')),
            ],
        ),
    ]
