# Generated by Django 2.1.4 on 2020-05-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_test1'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='q',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
