# Generated by Django 2.1.4 on 2020-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_test1_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='q',
        ),
        migrations.AlterField(
            model_name='test1',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
