# Generated by Django 2.1.4 on 2020-05-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200525_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
