# Generated by Django 2.1.4 on 2020-05-24 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200525_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.SignUp'),
        ),
    ]
