# Generated by Django 2.1.4 on 2020-05-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20200525_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Phone',
        ),
    ]
