# Generated by Django 2.1.4 on 2020-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='endTime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='test2',
            name='startTime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
