# Generated by Django 2.1.4 on 2020-05-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_test2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='timeReq',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
