# Generated by Django 2.1.4 on 2020-05-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20200530_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='test2',
            name='startTime',
        ),
    ]
