# Generated by Django 2.1.4 on 2020-05-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20200526_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='test2',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test2',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
