# Generated by Django 2.1.4 on 2020-05-29 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20200529_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='endTime',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='test2',
            name='startTime',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
    ]
