# Generated by Django 2.1.4 on 2020-05-29 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20200530_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='endTime',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 29, 19, 26, 13, 621173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test2',
            name='startTime',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 5, 29, 19, 26, 13, 621173, tzinfo=utc)),
        ),
    ]
