# Generated by Django 2.1.4 on 2020-05-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20200526_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='endTime',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test2',
            name='startTime',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test2',
            name='timeReq',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
