# Generated by Django 2.1.4 on 2020-05-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20200530_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2',
            name='timeReq',
        ),
    ]
