# Generated by Django 2.1.4 on 2020-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20200526_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='test2',
            name='startTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='test2',
            name='timeReq',
            field=models.DateTimeField(),
        ),
    ]
