# Generated by Django 2.1.4 on 2020-05-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20200528_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='timeReq',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
